FROM quay.io/keycloak/keycloak:latest as builder

# Enable health and metrics support
ENV KC_HEALTH_ENABLED=true
ENV KC_METRICS_ENABLED=true

# Configure a database vendor
ENV KC_DB=postgres

COPY theme /opt/keycloak/themes
COPY target/keycloak-extensions.jar /opt/keycloak/providers/
COPY docker-entrypoint.sh /opt/jboss/tools

WORKDIR /opt/keycloak
# for demonstration purposes only, please make sure to use proper certificates in production instead
RUN keytool -genkeypair -storepass password -storetype PKCS12 -keyalg RSA -keysize 2048 -dname "CN=server" -alias server -ext "SAN:c=DNS:localhost,IP:127.0.0.1" -keystore conf/server.keystore
RUN /opt/keycloak/bin/kc.sh build

FROM quay.io/keycloak/keycloak:latest
COPY --from=builder /opt/keycloak/ /opt/keycloak/

# change these values to point to a running postgres instance
ENV KC_DB=postgres
ENV KC_DB_URL=jdbc:postgresql://ec2-52-215-209-64.eu-west-1.compute.amazonaws.com:5432/dtud8rp5052gm
ENV KC_DB_USERNAME=dpjvphjqqwwcbz
ENV KC_DB_PASSWORD=7822931e63a0f618797165178153ee60f4051dad48c43138a92c2cfb35158de3
ENV KC_HOSTNAME=ec2-52-215-209-64.eu-west-1.compute.amazonaws.com

ENTRYPOINT ["/opt/keycloak/bin/kc.sh"]
CMD ["start-dev"]

